DEFAULT_FORM_STASH = "_default"
DEFAULT_ERROR_MAIN_KEY = "Error_Main"
DEFAULT_ERROR_MAIN_TEXT = "There was an error with your form submission."
DEFAULT_ERROR_FIELD_TEXT = "This field has an error."
DEFAULT_ERROR_NOTHING_SUBMITTED = "Nothing submitted."
